### ISSUE TITLE
Improve accuracy of the model

### ISSUE THREAD

**Issue by MoKaif** [MoKaif/Stroke_Prediction_System#2]

**Comment by Ramghosh16RG** [comment]
Hi @MoKaif,
I think I know a way to make the existing model better. It could be more accurate, like 93% accurate. Can you let me help with this? I'd like to give it a try. #2

**Comment by MoKaif** [comment]
Absolutely, @Ramghosh16RG 

Thanks for stepping up to contribute. I appreciate your willingness. I've assigned the issue to you. Feel free to dive in and solve this issue.

If you have any questions or need assistance along the way, don't hesitate to reach out. Looking forward to seeing your progress on this.

**Comment by Ramghosh16RG** [comment]
@MoKaif #2 Thank you for your kind words and for entrusting me with this opportunity. I'm excited to take on the challenge and contribute to the best of my abilities. Your support means a lot, and I'll definitely reach out if I need any guidance. Looking forward to making progress on this issue!
